# Website settings
url: "https://www.andreitihoan.com"

# Internal nav
nav:
  main:
    projects: "/projects"
    writing: "/writing"
  writing:
    all: "/writing"
    tags: "/writing/tags"

# Bio settings
copyright_holder_name: "Yevgeniy Brikman"
name: "Andrei Tihoan"
description: "The home page of Andrei Tihoan, Computer Science and Artificial Intelligence Master's graduate"
thumbnail_path: "profile-photos/Andrei-Tihoan-medium-grey.jpg"
website_repo_url: "https://github.com/AndreiTih/andrei-tihoan-homepage"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/andrei-tihoan/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/AndreiTih"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:andrei.tihoan0@gmail.com"
    label: "Email"
    value: "andrei.tihoan0@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'GMT'
repository: brikis98/yevgeniy-brikman-homepage

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
